version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#     - ~/data/docker-mysql:/var/lib/mysql

  manage:
    build: ./manage
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      APPSTORE_BUNDLE: ${APPSTORE_BUNDLE}
      RSYNC_HOST: ${RSYNC_HOST}
      RSYNC_USERNAME: ${RSYNC_USERNAME}
      RSYNC_PASSWORD: ${RSYNC_PASSWORD}
      HOST_ALLOW: ${HOST_ALLOW}
      # dev or prod
      RUN_MODE: dev
    ports:
      - "873:873"

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:8086:8086"
      - "8087:8087"
    depends_on:
      - manage
